package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name="acceso"
    ,catalog="contrataciondb"
)
public class Acceso  implements java.io.Serializable {


     private Integer idAcceso;
     private Usuario usuario;
     private String ip;
     private Date fechaHora;
     private String origen;

    public Acceso() {
    }

	
    public Acceso(String ip, Date fechaHora, String origen) {
        this.ip = ip;
        this.fechaHora = fechaHora;
        this.origen = origen;
    }
    public Acceso(Usuario usuario, String ip, Date fechaHora, String origen) {
       this.usuario = usuario;
       this.ip = ip;
       this.fechaHora = fechaHora;
       this.origen = origen;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAcceso", unique=true, nullable=false)
    public Integer getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(Integer idAcceso) {
        this.idAcceso = idAcceso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idUsuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ip", nullable=false, length=39)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaHora", nullable=false, length=10)
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    
    @Column(name="origen", nullable=false, length=400)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }




}


