package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Busqueda generated by hbm2java
 */
@Entity
@Table(name="busqueda"
    ,catalog="contrataciondb"
)
public class Busqueda  implements java.io.Serializable {


     private Integer idBusqueda;
     private Usuario usuario;
     private String valor;
     private Date fechaHora;

    public Busqueda() {
    }

	
    public Busqueda(String valor, Date fechaHora) {
        this.valor = valor;
        this.fechaHora = fechaHora;
    }
    public Busqueda(Usuario usuario, String valor, Date fechaHora) {
       this.usuario = usuario;
       this.valor = valor;
       this.fechaHora = fechaHora;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBusqueda", unique=true, nullable=false)
    public Integer getIdBusqueda() {
        return this.idBusqueda;
    }
    
    public void setIdBusqueda(Integer idBusqueda) {
        this.idBusqueda = idBusqueda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idUsuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="valor", nullable=false, length=45)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaHora", nullable=false, length=10)
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }




}


