package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,catalog="contrataciondb"
)
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private Categoria categoria;
     private String nombre;
     private boolean estado;
     private Set trabajos = new HashSet(0);
     private Set etiquetas = new HashSet(0);
     private Set categorias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombre, boolean estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Categoria(Categoria categoria, String nombre, boolean estado, Set trabajos, Set etiquetas, Set categorias) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.estado = estado;
       this.trabajos = trabajos;
       this.etiquetas = etiquetas;
       this.categorias = categorias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategoria", unique=true, nullable=false)
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    @ManyToOne(cascade={CascadeType.ALL})
    @JoinColumn(name = "categoria_idCategoria")
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getEtiquetas() {
        return this.etiquetas;
    }
    
    public void setEtiquetas(Set etiquetas) {
        this.etiquetas = etiquetas;
    }

@OneToMany(mappedBy="categoria")
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }

    //Se crea para utilizar selectOneMenu
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idCategoria != null ? idCategoria.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Categoria)) {
            return false;
        }
        Categoria other = (Categoria) object;
        if ((this.idCategoria == null && other.idCategoria != null) || (this.idCategoria != null && !this.idCategoria.equals(other.idCategoria))) {
            return false;
        }
        return true;
    }


}


