package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comision generated by hbm2java
 */
@Entity
@Table(name="comision"
    ,catalog="contrataciondb"
)
public class Comision  implements java.io.Serializable {


     private Integer idcomision;
     private BigDecimal valor;
     private Date fechaCreacion;
     private boolean estado;
     private Set cotizacions = new HashSet(0);

    public Comision() {
    }

	
    public Comision(BigDecimal valor, Date fechaCreacion, boolean estado) {
        this.valor = valor;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Comision(BigDecimal valor, Date fechaCreacion, boolean estado, Set cotizacions) {
       this.valor = valor;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.cotizacions = cotizacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomision", unique=true, nullable=false)
    public Integer getIdcomision() {
        return this.idcomision;
    }
    
    public void setIdcomision(Integer idcomision) {
        this.idcomision = idcomision;
    }

    
    @Column(name="valor", nullable=false, precision=1, scale=1)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comision")
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }




}


