package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="contrato"
    ,catalog="contrataciondb"
)
public class Contrato  implements java.io.Serializable {


     private Integer idContrato;
     private Cotizacion cotizacion;
     private Liquidacion liquidacion;
     private Usuario usuario;
     private Date fecha;
     private String direccion;
     private Integer calificacion;
     private String comentario;
     private int valorTotal;
     private boolean estado;
     private Set pagos = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(Cotizacion cotizacion, Date fecha, String direccion, int valorTotal, boolean estado) {
        this.cotizacion = cotizacion;
        this.fecha = fecha;
        this.direccion = direccion;
        this.valorTotal = valorTotal;
        this.estado = estado;
    }
    public Contrato(Cotizacion cotizacion, Liquidacion liquidacion, Usuario usuario, Date fecha, String direccion, Integer calificacion, String comentario, int valorTotal, boolean estado, Set pagos) {
       this.cotizacion = cotizacion;
       this.liquidacion = liquidacion;
       this.usuario = usuario;
       this.fecha = fecha;
       this.direccion = direccion;
       this.calificacion = calificacion;
       this.comentario = comentario;
       this.valorTotal = valorTotal;
       this.estado = estado;
       this.pagos = pagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContrato", unique=true, nullable=false)
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cotizacion_idCotizacion", nullable=false)
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="liquidacion_idliquidacion")
    public Liquidacion getLiquidacion() {
        return this.liquidacion;
    }
    
    public void setLiquidacion(Liquidacion liquidacion) {
        this.liquidacion = liquidacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idUsuarioModificador")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="calificacion")
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }

    
    @Column(name="comentario", length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="valor_total", nullable=false)
    public int getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(int valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


