package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cotizacion generated by hbm2java
 */
@Entity
@Table(name="cotizacion"
    ,catalog="contrataciondb"
)
public class Cotizacion  implements java.io.Serializable {


     private Integer idCotizacion;
     private Comision comision;
     private Oferta oferta;
     private Usuario usuario;
     private int valorPresupuesto;
     private int unidadesTrabajo;
     private String descripcion;
     private Date fechaTrabajo;
     private Date fechaSolicitud;
     private boolean respuesta;
     private Integer valorContrapropuesta;
     private Date fechaContraPropuestaRespuesta;
     private Date fechaRespuesta;
     private Date fechaEstricta;
     private boolean estado;
     private Set contratos = new HashSet(0);

    public Cotizacion() {
    }

	
    public Cotizacion(Comision comision, Oferta oferta, Usuario usuario, int valorPresupuesto, int unidadesTrabajo, Date fechaTrabajo, Date fechaSolicitud, boolean respuesta, boolean estado) {
        this.comision = comision;
        this.oferta = oferta;
        this.usuario = usuario;
        this.valorPresupuesto = valorPresupuesto;
        this.unidadesTrabajo = unidadesTrabajo;
        this.fechaTrabajo = fechaTrabajo;
        this.fechaSolicitud = fechaSolicitud;
        this.respuesta = respuesta;
        this.estado = estado;
    }
    public Cotizacion(Comision comision, Oferta oferta, Usuario usuario, int valorPresupuesto, int unidadesTrabajo, String descripcion, Date fechaTrabajo, Date fechaSolicitud, boolean respuesta, Integer valorContrapropuesta, Date fechaContraPropuestaRespuesta, Date fechaRespuesta, Date fechaEstricta, boolean estado, Set contratos) {
       this.comision = comision;
       this.oferta = oferta;
       this.usuario = usuario;
       this.valorPresupuesto = valorPresupuesto;
       this.unidadesTrabajo = unidadesTrabajo;
       this.descripcion = descripcion;
       this.fechaTrabajo = fechaTrabajo;
       this.fechaSolicitud = fechaSolicitud;
       this.respuesta = respuesta;
       this.valorContrapropuesta = valorContrapropuesta;
       this.fechaContraPropuestaRespuesta = fechaContraPropuestaRespuesta;
       this.fechaRespuesta = fechaRespuesta;
       this.fechaEstricta = fechaEstricta;
       this.estado = estado;
       this.contratos = contratos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCotizacion", unique=true, nullable=false)
    public Integer getIdCotizacion() {
        return this.idCotizacion;
    }
    
    public void setIdCotizacion(Integer idCotizacion) {
        this.idCotizacion = idCotizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comision_idcomision", nullable=false)
    public Comision getComision() {
        return this.comision;
    }
    
    public void setComision(Comision comision) {
        this.comision = comision;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oferta_idOferta", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idUsuarioContratador", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="valorPresupuesto", nullable=false)
    public int getValorPresupuesto() {
        return this.valorPresupuesto;
    }
    
    public void setValorPresupuesto(int valorPresupuesto) {
        this.valorPresupuesto = valorPresupuesto;
    }

    
    @Column(name="unidadesTrabajo", nullable=false)
    public int getUnidadesTrabajo() {
        return this.unidadesTrabajo;
    }
    
    public void setUnidadesTrabajo(int unidadesTrabajo) {
        this.unidadesTrabajo = unidadesTrabajo;
    }

    
    @Column(name="descripcion", length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaTrabajo", nullable=false, length=10)
    public Date getFechaTrabajo() {
        return this.fechaTrabajo;
    }
    
    public void setFechaTrabajo(Date fechaTrabajo) {
        this.fechaTrabajo = fechaTrabajo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaSolicitud", nullable=false, length=10)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    
    @Column(name="Respuesta", nullable=false)
    public boolean isRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(boolean respuesta) {
        this.respuesta = respuesta;
    }

    
    @Column(name="valorContrapropuesta")
    public Integer getValorContrapropuesta() {
        return this.valorContrapropuesta;
    }
    
    public void setValorContrapropuesta(Integer valorContrapropuesta) {
        this.valorContrapropuesta = valorContrapropuesta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaContraPropuestaRespuesta", length=10)
    public Date getFechaContraPropuestaRespuesta() {
        return this.fechaContraPropuestaRespuesta;
    }
    
    public void setFechaContraPropuestaRespuesta(Date fechaContraPropuestaRespuesta) {
        this.fechaContraPropuestaRespuesta = fechaContraPropuestaRespuesta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaRespuesta", length=10)
    public Date getFechaRespuesta() {
        return this.fechaRespuesta;
    }
    
    public void setFechaRespuesta(Date fechaRespuesta) {
        this.fechaRespuesta = fechaRespuesta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaEstricta", length=10)
    public Date getFechaEstricta() {
        return this.fechaEstricta;
    }
    
    public void setFechaEstricta(Date fechaEstricta) {
        this.fechaEstricta = fechaEstricta;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cotizacion")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }


    //Se crea para utilizar selectOneMenu
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idCotizacion != null ? idCotizacion.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Cotizacion)) {
            return false;
        }
        Cotizacion other = (Cotizacion) object;
        if ((this.idCotizacion == null && other.idCotizacion != null) || (this.idCotizacion != null && !this.idCotizacion.equals(other.idCotizacion))) {
            return false;
        }
        return true;
    }

}


