package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Etiqueta generated by hbm2java
 */
@Entity
@Table(name="etiqueta"
    ,catalog="contrataciondb"
)
public class Etiqueta  implements java.io.Serializable {


     private Integer idEtiqueta;
     private Categoria categoria;
     private String nombre;
     private boolean estado;

    public Etiqueta() {
    }

    public Etiqueta(Categoria categoria, String nombre, boolean estado) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEtiqueta", unique=true, nullable=false)
    public Integer getIdEtiqueta() {
        return this.idEtiqueta;
    }
    
    public void setIdEtiqueta(Integer idEtiqueta) {
        this.idEtiqueta = idEtiqueta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria_idCategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


