package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagenes generated by hbm2java
 */
@Entity
@Table(name="imagenes"
    ,catalog="contrataciondb"
)
public class Imagenes  implements java.io.Serializable {


     private Integer idImagenes;
     private Portafolio portafolio;
     private String url;
     private boolean estado;

    public Imagenes() {
    }

    public Imagenes(Portafolio portafolio, String url, boolean estado) {
       this.portafolio = portafolio;
       this.url = url;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idImagenes", unique=true, nullable=false)
    public Integer getIdImagenes() {
        return this.idImagenes;
    }
    
    public void setIdImagenes(Integer idImagenes) {
        this.idImagenes = idImagenes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="portafolio_idPortafolio", nullable=false)
    public Portafolio getPortafolio() {
        return this.portafolio;
    }
    
    public void setPortafolio(Portafolio portafolio) {
        this.portafolio = portafolio;
    }

    
    @Column(name="url", nullable=false, length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


