package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jornada generated by hbm2java
 */
@Entity
@Table(name="jornada"
    ,catalog="contrataciondb"
)
public class Jornada  implements java.io.Serializable {


     private Integer idJornada;
     private String nombre;
     private Set ofertas = new HashSet(0);

    public Jornada() {
    }

	
    public Jornada(String nombre) {
        this.nombre = nombre;
    }
    public Jornada(String nombre, Set ofertas) {
       this.nombre = nombre;
       this.ofertas = ofertas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idJornada", unique=true, nullable=false)
    public Integer getIdJornada() {
        return this.idJornada;
    }
    
    public void setIdJornada(Integer idJornada) {
        this.idJornada = idJornada;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jornada")
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }




}


