package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicionTrabajo generated by hbm2java
 */
@Entity
@Table(name="medicion_trabajo"
    ,catalog="contrataciondb"
)
public class MedicionTrabajo  implements java.io.Serializable {


     private Integer idMedicionTrabajo;
     private String nombre;
     private boolean estado;
     private Set trabajos = new HashSet(0);

    public MedicionTrabajo() {
    }

	
    public MedicionTrabajo(String nombre, boolean estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public MedicionTrabajo(String nombre, boolean estado, Set trabajos) {
       this.nombre = nombre;
       this.estado = estado;
       this.trabajos = trabajos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMedicionTrabajo", unique=true, nullable=false)
    public Integer getIdMedicionTrabajo() {
        return this.idMedicionTrabajo;
    }
    
    public void setIdMedicionTrabajo(Integer idMedicionTrabajo) {
        this.idMedicionTrabajo = idMedicionTrabajo;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicionTrabajo")
    public Set getTrabajos() {
        return this.trabajos;
    }
    
    public void setTrabajos(Set trabajos) {
        this.trabajos = trabajos;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof MedicionTrabajo)) {
            return false;
        }
        MedicionTrabajo other = (MedicionTrabajo) object;
        if ((this.idMedicionTrabajo == null && other.idMedicionTrabajo != null) || (this.idMedicionTrabajo != null && !this.idMedicionTrabajo.equals(other.idMedicionTrabajo))) {
            return false;
        }
        return true;
    }


}


