package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oferta generated by hbm2java
 */
@Entity
@Table(name="oferta"
    ,catalog="contrataciondb"
)
public class Oferta  implements java.io.Serializable {


     private Integer idOferta;
     private Jornada jornada;
     private Trabajo trabajo;
     private Usuario usuario;
     private int costo;
     private Date fechaCreacion;
     private Date fechaUltimaActualizacion;
     private Date fechaLimite;
     private boolean estado;
     private Set portafolios = new HashSet(0);
     private Set cotizacions = new HashSet(0);

    public Oferta() {
    }

	
    public Oferta(Jornada jornada, Trabajo trabajo, Usuario usuario, int costo, Date fechaCreacion, boolean estado) {
        this.jornada = jornada;
        this.trabajo = trabajo;
        this.usuario = usuario;
        this.costo = costo;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Oferta(Jornada jornada, Trabajo trabajo, Usuario usuario, int costo, Date fechaCreacion, Date fechaUltimaActualizacion, Date fechaLimite, boolean estado, Set portafolios, Set cotizacions) {
       this.jornada = jornada;
       this.trabajo = trabajo;
       this.usuario = usuario;
       this.costo = costo;
       this.fechaCreacion = fechaCreacion;
       this.fechaUltimaActualizacion = fechaUltimaActualizacion;
       this.fechaLimite = fechaLimite;
       this.estado = estado;
       this.portafolios = portafolios;
       this.cotizacions = cotizacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idOferta", unique=true, nullable=false)
    public Integer getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Jornada_idJornada", nullable=false)
    public Jornada getJornada() {
        return this.jornada;
    }
    
    public void setJornada(Jornada jornada) {
        this.jornada = jornada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trabajo_idTrabajo", nullable=false)
    public Trabajo getTrabajo() {
        return this.trabajo;
    }
    
    public void setTrabajo(Trabajo trabajo) {
        this.trabajo = trabajo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idUsuarioOferta", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="costo", nullable=false)
    public int getCosto() {
        return this.costo;
    }
    
    public void setCosto(int costo) {
        this.costo = costo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ultima_actualizacion", length=10)
    public Date getFechaUltimaActualizacion() {
        return this.fechaUltimaActualizacion;
    }
    
    public void setFechaUltimaActualizacion(Date fechaUltimaActualizacion) {
        this.fechaUltimaActualizacion = fechaUltimaActualizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_limite", length=10)
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oferta")
    public Set getPortafolios() {
        return this.portafolios;
    }
    
    public void setPortafolios(Set portafolios) {
        this.portafolios = portafolios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oferta")
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }




}


