package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Portafolio generated by hbm2java
 */
@Entity
@Table(name="portafolio"
    ,catalog="contrataciondb"
)
public class Portafolio  implements java.io.Serializable {


     private Integer idPortafolio;
     private Oferta oferta;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaUltimaActualizacion;
     private boolean estado;
     private Set imageneses = new HashSet(0);

    public Portafolio() {
    }

	
    public Portafolio(Oferta oferta, String descripcion, Date fechaCreacion, boolean estado) {
        this.oferta = oferta;
        this.descripcion = descripcion;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Portafolio(Oferta oferta, String descripcion, Date fechaCreacion, Date fechaUltimaActualizacion, boolean estado, Set imageneses) {
       this.oferta = oferta;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaUltimaActualizacion = fechaUltimaActualizacion;
       this.estado = estado;
       this.imageneses = imageneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPortafolio", unique=true, nullable=false)
    public Integer getIdPortafolio() {
        return this.idPortafolio;
    }
    
    public void setIdPortafolio(Integer idPortafolio) {
        this.idPortafolio = idPortafolio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oferta_idOferta", nullable=false)
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

    
    @Column(name="descripcion", nullable=false, length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ultima_actualizacion", length=10)
    public Date getFechaUltimaActualizacion() {
        return this.fechaUltimaActualizacion;
    }
    
    public void setFechaUltimaActualizacion(Date fechaUltimaActualizacion) {
        this.fechaUltimaActualizacion = fechaUltimaActualizacion;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="portafolio")
    public Set getImageneses() {
        return this.imageneses;
    }
    
    public void setImageneses(Set imageneses) {
        this.imageneses = imageneses;
    }




}


