package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name="tipo_pago"
    ,catalog="contrataciondb"
)
public class TipoPago  implements java.io.Serializable {


     private Integer idTipoPago;
     private String nombre;
     private boolean estado;
     private Set pagos = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(String nombre, boolean estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public TipoPago(String nombre, boolean estado, Set pagos) {
       this.nombre = nombre;
       this.estado = estado;
       this.pagos = pagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoPago", unique=true, nullable=false)
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPago")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


