package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trabajo generated by hbm2java
 */
@Entity
@Table(name="trabajo"
    ,catalog="contrataciondb"
)
public class Trabajo  implements java.io.Serializable {


     private Integer idTrabajo;
     private Categoria categoria;
     private MedicionTrabajo medicionTrabajo;
     private String titulo;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaUltimaActualizacion;
     private boolean estado;
     private Set ofertas = new HashSet(0);

    public Trabajo() {
    }

	
    public Trabajo(Categoria categoria, MedicionTrabajo medicionTrabajo, String titulo, String descripcion, Date fechaCreacion, boolean estado) {
        this.categoria = categoria;
        this.medicionTrabajo = medicionTrabajo;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Trabajo(Categoria categoria, MedicionTrabajo medicionTrabajo, String titulo, String descripcion, Date fechaCreacion, Date fechaUltimaActualizacion, boolean estado, Set ofertas) {
       this.categoria = categoria;
       this.medicionTrabajo = medicionTrabajo;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaUltimaActualizacion = fechaUltimaActualizacion;
       this.estado = estado;
       this.ofertas = ofertas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTrabajo", unique=true, nullable=false)
    public Integer getIdTrabajo() {
        return this.idTrabajo;
    }
    
    public void setIdTrabajo(Integer idTrabajo) {
        this.idTrabajo = idTrabajo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria_idCategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="medicion_trabajo_idMedicionTrabajo", nullable=false)
    public MedicionTrabajo getMedicionTrabajo() {
        return this.medicionTrabajo;
    }
    
    public void setMedicionTrabajo(MedicionTrabajo medicionTrabajo) {
        this.medicionTrabajo = medicionTrabajo;
    }

    
    @Column(name="titulo", nullable=false, length=45)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="descripcion", nullable=false, length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ultima_actualizacion", length=10)
    public Date getFechaUltimaActualizacion() {
        return this.fechaUltimaActualizacion;
    }
    
    public void setFechaUltimaActualizacion(Date fechaUltimaActualizacion) {
        this.fechaUltimaActualizacion = fechaUltimaActualizacion;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajo")
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }




}


