package model;
// Generated 4/07/2016 02:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="contrataciondb"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Ubicacion ubicacion;
     private String email;
     private String emailAlterno;
     private String emailAlterno2;
     private String contrasena;
     private String nombres;
     private String apellidos;
     private int documentoIdentidad;
     private String telefono;
     private String direccion;
     private String foto;
     private String perfil;
     private String experiencia;
     private String profesion;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private boolean estado;
     private Set contratos = new HashSet(0);
     private Set rols = new HashSet(0);
     private Set ofertas = new HashSet(0);
     private Set accesos = new HashSet(0);
     private Set busquedas = new HashSet(0);
     private Set cotizacions = new HashSet(0);
     private Set liquidacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Ubicacion ubicacion, String email, String contrasena, String nombres, String apellidos, int documentoIdentidad, String telefono, String direccion, String foto, Date fechaCreacion, boolean estado) {
        this.ubicacion = ubicacion;
        this.email = email;
        this.contrasena = contrasena;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.documentoIdentidad = documentoIdentidad;
        this.telefono = telefono;
        this.direccion = direccion;
        this.foto = foto;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Usuario(Ubicacion ubicacion, String email, String emailAlterno, String emailAlterno2, String contrasena, String nombres, String apellidos, int documentoIdentidad, String telefono, String direccion, String foto, String perfil, String experiencia, String profesion, Date fechaCreacion, Date fechaActualizacion, boolean estado, Set contratos, Set rols, Set ofertas, Set accesos, Set busquedas, Set cotizacions, Set liquidacions) {
       this.ubicacion = ubicacion;
       this.email = email;
       this.emailAlterno = emailAlterno;
       this.emailAlterno2 = emailAlterno2;
       this.contrasena = contrasena;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.documentoIdentidad = documentoIdentidad;
       this.telefono = telefono;
       this.direccion = direccion;
       this.foto = foto;
       this.perfil = perfil;
       this.experiencia = experiencia;
       this.profesion = profesion;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.estado = estado;
       this.contratos = contratos;
       this.rols = rols;
       this.ofertas = ofertas;
       this.accesos = accesos;
       this.busquedas = busquedas;
       this.cotizacions = cotizacions;
       this.liquidacions = liquidacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ubicacion_idUbicacion", nullable=false)
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="emailAlterno", length=45)
    public String getEmailAlterno() {
        return this.emailAlterno;
    }
    
    public void setEmailAlterno(String emailAlterno) {
        this.emailAlterno = emailAlterno;
    }

    
    @Column(name="emailAlterno2", length=45)
    public String getEmailAlterno2() {
        return this.emailAlterno2;
    }
    
    public void setEmailAlterno2(String emailAlterno2) {
        this.emailAlterno2 = emailAlterno2;
    }

    
    @Column(name="contrasena", nullable=false, length=45)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="documento_identidad", nullable=false)
    public int getDocumentoIdentidad() {
        return this.documentoIdentidad;
    }
    
    public void setDocumentoIdentidad(int documentoIdentidad) {
        this.documentoIdentidad = documentoIdentidad;
    }

    
    @Column(name="telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="foto", nullable=false, length=100)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="perfil", length=300)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="experiencia", length=300)
    public String getExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(String experiencia) {
        this.experiencia = experiencia;
    }

    
    @Column(name="profesion", length=300)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_actualizacion", length=10)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }

    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getBusquedas() {
        return this.busquedas;
    }
    
    public void setBusquedas(Set busquedas) {
        this.busquedas = busquedas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getLiquidacions() {
        return this.liquidacions;
    }
    
    public void setLiquidacions(Set liquidacions) {
        this.liquidacions = liquidacions;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", ubicacion=" + ubicacion + ", email=" + email + ", emailAlterno=" + emailAlterno + ", emailAlterno2=" + emailAlterno2 + ", contrasena=" + contrasena + ", nombres=" + nombres + ", apellidos=" + apellidos + ", documentoIdentidad=" + documentoIdentidad + ", telefono=" + telefono + ", direccion=" + direccion + ", foto=" + foto + ", perfil=" + perfil + ", experiencia=" + experiencia + ", profesion=" + profesion + ", fechaCreacion=" + fechaCreacion + ", fechaActualizacion=" + fechaActualizacion + ", estado=" + estado + ", contratos=" + contratos + ", rols=" + rols + ", ofertas=" + ofertas + ", accesos=" + accesos + ", busquedas=" + busquedas + ", cotizacions=" + cotizacions + ", liquidacions=" + liquidacions + '}';
    }




}


